"""Post-Market Monitoring Plan generator — EU AI Act Article 72 compliance.

Produces a PMM plan template that references Pass³ baseline results
as the drift detection standard. This satisfies the Art. 72 requirement
that a PMM system be established as a condition of market placement.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .models import ScanReport


def generate_monitor_plan(
    scan_report: ScanReport | None = None,
    target_name: str = "AI Agent System",
    output_path: str = "./preseal-monitor-plan.md",
) -> str:
    """Generate an Article 72 Post-Market Monitoring plan.

    If scan_report is provided, references specific baseline metrics.
    Otherwise generates a template with placeholders.
    """
    now = datetime.now(timezone.utc)

    if scan_report:
        baseline_section = _baseline_from_report(scan_report)
        target_name = scan_report.target
    else:
        baseline_section = _baseline_placeholder()

    plan = f"""# Post-Market Monitoring Plan
## EU AI Act Article 72 Compliance

**System:** {target_name}
**Date Established:** {now.strftime('%Y-%m-%d')}
**Generated by:** preseal v{scan_report.version if scan_report else '0.4.0'}
**Methodology Reference:** https://preseal.org (Pass³ Testing Methodology)

---

## 1. Purpose and Scope

This Post-Market Monitoring (PMM) plan is established in accordance with EU AI Act
Article 72, which requires providers of high-risk AI systems to establish and document
a post-market monitoring system proportionate to the nature of the AI technologies
and risks of the high-risk AI system.

This plan defines:
- What metrics are monitored after deployment
- How drift from pre-deployment baselines is detected
- When re-testing is triggered
- How serious incidents are identified and reported (Art. 73)

---

## 2. Pre-Deployment Baseline (Pass³ Reference)

{baseline_section}

---

## 3. Monitoring Triggers

The following events REQUIRE re-running `preseal scan` and comparing against baseline:

| Trigger | Rationale | Action |
|---------|-----------|--------|
| Model version change | Different model = different behavior distribution | Full re-scan |
| System prompt modification | Prompt changes can remove security defenses | Full re-scan |
| Tool addition/removal | New tools expand attack surface | Full re-scan + audit |
| Temperature parameter change | Higher temperature = more non-deterministic | Full re-scan |
| Framework/SDK version upgrade | Upstream changes may alter behavior | Quick scan |
| 30 days elapsed since last scan | Drift detection interval | Quick scan |
| User-reported anomalous behavior | Potential incident | Targeted re-scan |

**Command:** `preseal diff --target <module:agent> --baseline .preseal/baseline.json`

---

## 4. Drift Detection Methodology

Drift is defined as any attack transitioning between verdict categories:

| Transition | Severity | Required Action |
|------------|----------|-----------------|
| PASS → STRUCTURAL | CRITICAL | Immediate remediation. Consider Art. 73 reporting. |
| PASS → STOCHASTIC | HIGH | Investigation required within 72 hours |
| STOCHASTIC → STRUCTURAL | HIGH | Remediation required before next release |
| STRUCTURAL → PASS | POSITIVE | Document fix, update baseline |

**Detection command:** `preseal diff` compares current scan against stored baseline
and reports all transitions with confidence intervals.

---

## 5. Serious Incident Reporting (Article 73)

A **serious incident** requiring notification to the national market surveillance
authority within 15 calendar days includes:

- Agent causes death or serious damage to health, property, or environment
- Agent causes serious and irreversible disruption of critical infrastructure
- Agent causes harm leading to breach of fundamental rights obligations

**Preseal indicators that may signal a serious incident:**
- Any attack class transitioning from PASS to STRUCTURAL in production
- Canary token detection in production logs (credential exfiltration)
- Scope violation detection on production data paths
- Multi-turn trust escalation succeeding on real user interactions

**Incident response:**
1. Immediately halt agent operation if harm is ongoing
2. Run `preseal scan --target <agent>` to characterize the vulnerability
3. Document findings using `preseal report --format pdf`
4. Notify national authority within 15 days with report attached
5. Implement fix, re-scan, update baseline

---

## 6. Integration with Runtime Monitoring Tools

This PMM plan is designed to work alongside runtime monitoring systems.
Preseal provides the PRE-DEPLOYMENT BASELINE; runtime tools provide
CONTINUOUS OPERATIONAL MONITORING:

| Layer | Tool | Role |
|-------|------|------|
| Pre-deployment | preseal (Pass³) | Establishes behavior baseline, produces conformity evidence |
| Runtime | Apollo Watcher / nono / Pipelock / custom | Monitors for drift from baseline, blocks dangerous actions |
| Incident | preseal report | Documents incident with compliance mapping for Art. 73 |

**Feedback loop (Article 9 "continuous risk management"):**
1. Preseal scan → establishes baseline
2. Runtime monitor → detects anomalies against baseline
3. Anomaly triggers → preseal re-scan
4. New findings → update baseline + test suite
5. Repeat at each system modification

---

## 7. Documentation and Record-Keeping (Article 12)

The following records must be maintained:

| Record | Retention | Location |
|--------|-----------|----------|
| Preseal scan reports (JSON) | System lifetime + 10 years | `.preseal/reports/` |
| Baselines | Each version, indefinitely | `.preseal/baseline.json` |
| Conformity reports (PDF) | System lifetime + 10 years | Compliance file |
| Incident reports | 10 years minimum | Authority + internal |
| This PMM plan | Current version + all historical | Compliance file |

---

## 8. Responsible Persons

| Role | Responsibility |
|------|---------------|
| Provider (AI system developer) | Establishing and operating PMM system |
| Deployer | Monitoring system in use context, reporting incidents |
| Quality Manager | Maintaining documentation, conducting periodic reviews |
| Security Officer | Reviewing scan results, authorizing remediation |

---

## 9. Review Schedule

This PMM plan shall be reviewed and updated:
- At least annually
- After any serious incident
- After significant system modifications
- When new attack classes are identified in the threat landscape

---

*This plan was generated by [preseal](https://preseal.dev) as part of EU AI Act
Article 72 compliance. It references the Pass³ testing methodology published at
[preseal.org](https://preseal.org).*
"""
    Path(output_path).write_text(plan)
    return output_path


def _baseline_from_report(report: ScanReport) -> str:
    lines = ["The following pre-deployment test results serve as the monitoring baseline:\n"]
    lines.append(f"- **Target:** {report.target}")
    lines.append(f"- **Attacks tested:** {report.total_attacks}")
    trials = len(report.results[0].trials) if report.results else 0
    lines.append(f"- **Trials per attack:** {trials}")
    lines.append(f"- **Overall score:** {report.overall_score:.3f}")
    lines.append(f"- **Structural vulnerabilities:** {report.structural_count}")
    lines.append(f"- **Stochastic warnings:** {report.stochastic_count}")
    lines.append(f"- **Attacks passed:** {report.pass_count}")
    lines.append("")
    lines.append("| Attack | Verdict | Failure Rate | 95% CI |")
    lines.append("|--------|---------|--------------|--------|")
    for r in report.results:
        ci = r.failure_rate_ci
        lines.append(f"| {r.attack.name} | {r.verdict.value.upper()} | {r.failure_count}/{len(r.trials)} | [{ci[0]:.0%}, {ci[1]:.0%}] |")
    lines.append("")
    lines.append("**Baseline command:** `preseal scan --target <module:agent> --save-baseline`")
    return "\n".join(lines)


def _baseline_placeholder() -> str:
    return """*No scan results provided. Run `preseal scan --save-baseline` to establish baseline.*

After running a scan, re-generate this plan with:
```
preseal monitor-plan --scan ./preseal-report.json
```

The baseline table will be populated with specific attack results and confidence intervals.
"""
